### ISSUE TITLE
Submenu items on second render don't show up

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Menus#22]
Got weird behaviour with menu. 

When i render same menu twice in blade, on second render submenu items are not rendered.
For example if we have a menu

Menu1
- Submenu 1
- Submenu 2
Menu2
Menu3

Then if i do {!! Menus::render('main') !!} twice (second time for mobile menu) then on second render Submenu1 and Submenu2 are not being rendered. On first render everything is fine.

**Comment by sdebacker** [comment]
Thanks for catching it, I corrected the problem in 3.0.5.
