### ISSUE TITLE
Nesting Menus...

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/Menus#8]
Is there an easy way, or a best practice recommendation, to nest menus within other menus?
A structure like this.

```
mainmenu
  --link
  --link
  --submenu
      --link
      --link
  --link
```

And sorry to put this on the issue board, I know it's more of a question / feature request. 
If there's a better avenue for this sort of discussion? Let me know I'm happy to move further communication there. 

Thanks.

**Comment by sdebacker** [comment]
You can nest items by drag and drop like for pages. Does it answer your question ?

**Comment by eahrold** [comment]
Yes, absolutely. I have not idea how I missed this. Thanks.
